#Set prefix key to "ctrl + a" instead of "ctrl + b"
unbind C-b
set -g prefix C-a
bind C-a send-prefix


#basic global configuration
set -g default-terminal "screen-256color"

set -g default-terminal "tmux-256color"

set -ag terminal-overrides ",xterm-256color:RGB"
set-option -a terminal-features 'alacritty:RGB'

set -g mouse on
