#! /bin/sh

#terminate processes
processes=("sxhkd" "polybar")

for process in "${processes[@]}"; do
	if pgrep -f "$process"; then
		pkill -f "$process" >/dev/null
		sleep 0.25
	fi
done


bspc monitor -d '1' '2' '3' '4' '5' '6'

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

sxhkd &

bspc rule -a librewolf desktop=^2
bspc rule -a google-chrome desktop=^2

polybar mybar &
