[font]
size = 12

[font.normal]
family = "JetBrainsMono NF"
style = "Bold"

[cursor.style]
blinking = "on"

[cursor.vi_mode_style]
shape = "block"
blinking = "on"

[terminal.shell]
program = "/bin/zsh"
